[package]
name = "tldr"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }

eyre.workspace = true
clap.workspace = true
dirs.workspace = true
walkdir.workspace = true
